name: CI/CD Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  setup-buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.1.0 #https://github.com/docker/login-action
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta users
        id: users
        uses: docker/metadata-action@v4.3.0 # https://github.com/docker/metadata-action
        with:
          images: |
            kukun/web-assembly
          tags: |
            type=schedule,pattern=nightly
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=sha
            type=raw,value=latest

      - name: Build and push users production
        uses: docker/build-push-action@v4.0.0 # https://github.com/docker/build-push-action
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.users.outputs.tags }}

